version: "3"
services:
  app:
    # The application build
    build:
      # the context of the application
      context: .
    ports:
      # Maps the port to the
      # port on the container
      - "8000:8000"

    volumes:
      #  for automatic updating the
      # container if there is any change
      - ./app:/app

    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_NAME=app
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=123456

    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
